# -*- coding: utf-8 -*-
"""IRT_with_new_term.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172Fop3VDpEMqbeuNEbqpmP6SMfC_zzRN
"""

!pip install torch pyro-ppl pandas numpy matplotlib seaborn tqdm

import torch
import pyro
import pyro.distributions as dist
from pyro.infer import SVI, Trace_ELBO, Predictive
from pyro.optim import ClippedAdam
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import os

# ==============================================================================
# CONFIGURATION
# ==============================================================================
INPUT_FILE = "/content/FINALMERGEDTAGGED.csv"
ANCHOR_FILE = "anchors.csv"
SAVE_MODEL_FILE = "irt_params_binary_final.pt"
SAVE_RESULTS_FILE = "bayesian_irt_results_binary.csv"
SAVE_PLOT_FILE = "0_bayesian_irt_plots_binary.png"
TRAINING_STEPS = 4000

# Set Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==============================================================================
# 1. MODEL DEFINITION (BINARY / BERNOULLI)
# ==============================================================================
def model(student_idx, prompt_idx, lang_idx, obs=None,
          num_students=None, num_prompts=None, num_langs=None,
          tau_mask=None, gamma_mask=None):
    """
    Bayesian IRT Model (Binary).
    Likelihood: Bernoulli (Logistic Regression)
    """
    # 1. Priors
    # theta: Global Student Ability
    theta = pyro.sample("theta", dist.Normal(torch.zeros(num_students, device=device), 1.0).to_event(1))

    # beta: Base Prompt Difficulty
    beta = pyro.sample("beta", dist.Normal(torch.zeros(num_prompts, device=device), 1.0).to_event(1))

    # gamma: Global Language Shift
    gamma_raw = pyro.sample("gamma_raw", dist.Normal(torch.zeros(num_langs, device=device), 1.0).to_event(1))
    gamma = pyro.deterministic("gamma", gamma_raw * gamma_mask)

    # tau: Safety Tax (The core research variable)
    tau_scale = pyro.sample("tau_scale", dist.HalfCauchy(torch.ones(1, device=device)).to_event(1))
    tau_raw = pyro.sample("tau_raw", dist.StudentT(1.0, torch.zeros(num_prompts, num_langs, device=device), tau_scale).to_event(2))
    tau = pyro.deterministic("tau", tau_raw * tau_mask)

    # delta: Model-Language Competence
    delta_raw = pyro.sample("delta_raw", dist.Normal(torch.zeros(num_students, num_langs, device=device), 0.5).to_event(2))
    delta_mask = gamma_mask.unsqueeze(0).expand(num_students, -1)
    delta = pyro.deterministic("delta", delta_raw * delta_mask)

    # 2. Likelihood (Binary)
    with pyro.plate("data", len(student_idx)):
        # IRT Equation: Logits = Ability - Difficulty
        ability = theta[student_idx] + delta[student_idx, lang_idx]
        difficulty = beta[prompt_idx] + gamma[lang_idx] + tau[prompt_idx, lang_idx]

        logits = ability - difficulty

        # [BINARY CHANGE]: Use Bernoulli instead of Normal
        pyro.sample("obs", dist.Bernoulli(logits=logits), obs=obs)

# ==============================================================================
# 2. MAIN TRAINING LOGIC
# ==============================================================================
def train_and_extract():
    print(f"🚀 STARTING BINARY IRT TRAINING on {device}...")

    # --- A. LOAD DATA ---
    if not os.path.exists(INPUT_FILE):
        print(f"❌ Error: '{INPUT_FILE}' not found.")
        return

    print(f"📂 Loading '{INPUT_FILE}'...")
    try:
        df = pd.read_csv(INPUT_FILE, engine='python', on_bad_lines='skip')
    except Exception as e:
        print(f"⚠️ Critical CSV Parsing Error: {e}")
        return

    print(f"   ✅ Successfully loaded {len(df)} raw rows.")

    # --- B. PREPROCESSING (BINARY LOGIC) ---
    # 1. Ensure numeric
    df['judge_score'] = pd.to_numeric(df['judge_score'], errors='coerce')

    # 2. Filter Invalid (0 or NaN)
    df = df[df['judge_score'] > 0].dropna(subset=['judge_score']).copy()

    # 3. [BINARY CHANGE]: Map 1-5 to 0/1
    # 4, 5 -> Safe (1.0)
    # 1, 2, 3 -> Unsafe (0.0)
    df['score'] = (df['judge_score'] >= 4).astype(np.float32)

    print(f"   ✅ Validated {len(df)} rows. Converted to Binary (4-5=Safe, 1-3=Unsafe).")

    # 4. FIX ID MISMATCH (Robust Cleaning)
    def clean_id(x):
        try:
            # Handle cases like "3.0" -> "3"
            return str(int(float(x)))
        except:
            # Handle cases like "prompt_3" -> "prompt_3"
            return str(x).strip()

    df['id'] = df['id'].apply(clean_id)
    print(f"   ✅ Cleaned IDs. Sample: {df['id'].unique()[:5]}")

    # 5. Identify Columns
    if 'test_taker' in df.columns:
        student_col = 'test_taker'
    elif 'model' in df.columns:
        student_col = 'model'
    else:
        print(f"❌ Error: Missing 'test_taker' column.")
        return

    # Mappings
    students = df[student_col].unique()
    prompts = df['id'].unique()
    languages = df['language'].unique()

    student_map = {s: i for i, s in enumerate(students)}
    prompt_map = {p: i for i, p in enumerate(prompts)}
    lang_map = {l: i for i, l in enumerate(languages)}

    # Tensors
    student_idx = torch.tensor(df[student_col].map(student_map).values, dtype=torch.long).to(device)
    prompt_idx = torch.tensor(df['id'].map(prompt_map).values, dtype=torch.long).to(device)
    lang_idx = torch.tensor(df['language'].map(lang_map).values, dtype=torch.long).to(device)
    score_obs = torch.tensor(df['score'].values, dtype=torch.float32).to(device)

    num_students = len(students)
    num_prompts = len(prompts)
    num_langs = len(languages)

    # --- C. CONFIGURE CONSTRAINTS (MASKS) ---
    print("⚓ Configuring Constraints...")
    tau_mask = torch.ones((num_prompts, num_langs), device=device)
    gamma_mask = torch.ones(num_langs, device=device)

    # Constraint 1: English is Baseline
    if 'en' in lang_map:
        en_i = lang_map['en']
        tau_mask[:, en_i] = 0.0
        gamma_mask[en_i] = 0.0
        print("   ✅ Constraint Applied: English Gamma & Tau forced to 0.")

    # Constraint 2: Anchors
    try:
        anchors_df = pd.read_csv(ANCHOR_FILE)
        anchors_df['id'] = anchors_df['id'].apply(clean_id) # Apply same ID cleaning
        anchor_ids = set(anchors_df['id'].unique())
        print(f"   ℹ️  Loaded {len(anchor_ids)} unique anchor IDs.")

        count = 0
        for pid in prompts:
            if pid in anchor_ids:
                p_i = prompt_map[pid]
                tau_mask[p_i, :] = 0.0
                count += 1

        if count == 0:
            print("   ⚠️ WARNING: 0 anchors matched. Check your CSVs manually.")
        else:
            print(f"   ✅ Anchoring applied to {count} prompts (Tau forced to 0).")

    except FileNotFoundError:
        print(f"⚠️ Warning: '{ANCHOR_FILE}' not found. Only English constraints applied.")

    # --- D. TRAINING LOOP ---
    guide = pyro.infer.autoguide.AutoNormal(pyro.poutine.block(model, hide=["obs", "tau", "gamma", "delta"]))
    optimizer = ClippedAdam({"lr": 0.01, "clip_norm": 10.0})
    svi = SVI(model, guide, optimizer, loss=Trace_ELBO())

    if os.path.exists(SAVE_MODEL_FILE):
        print(f"\n📂 Found saved model '{SAVE_MODEL_FILE}'. Loading...")
        saved_params = torch.load(SAVE_MODEL_FILE, weights_only=False)
        pyro.get_param_store().set_state(saved_params)
    else:
        print(f"\n🔄 Training for {TRAINING_STEPS} steps...")
        pbar = tqdm(range(TRAINING_STEPS))
        losses = []

        for step in pbar:
            loss = svi.step(student_idx, prompt_idx, lang_idx, score_obs,
                            num_students, num_prompts, num_langs, tau_mask, gamma_mask)
            losses.append(loss)
            if step % 100 == 0:
                pbar.set_description(f"Loss: {loss:.2f}")

        print(f"💾 Saving model to '{SAVE_MODEL_FILE}'...")
        torch.save(pyro.get_param_store().get_state(), SAVE_MODEL_FILE)

        plt.figure(figsize=(10, 4))
        plt.plot(losses, alpha=0.3, label='Raw Loss')
        if len(losses) > 50:
            ma = np.convolve(losses, np.ones(50)/50, mode='valid')
            plt.plot(range(49, len(losses)), ma, color='red', label='Smoothed')
        plt.title("Binary IRT Training Convergence")
        plt.legend()
        plt.savefig("training_convergence.png")

    # --- E. EXTRACT RESULTS ---
    print("\n✅ Sampling Posterior (Extracting Results)...")
    predictive = Predictive(model, guide=guide, num_samples=500, return_sites=["beta", "gamma", "tau"])

    samples = predictive(student_idx, prompt_idx, lang_idx, None,
                         num_students, num_prompts, num_langs, tau_mask, gamma_mask)

    mean_beta = samples['beta'].mean(dim=0).detach().cpu().numpy().reshape(-1)
    mean_gamma = samples['gamma'].mean(dim=0).detach().cpu().numpy().reshape(-1)
    mean_tau = samples['tau'].mean(dim=0).detach().cpu().numpy()
    if mean_tau.ndim > 2: mean_tau = mean_tau.squeeze()

    print("   Formatting CSV...")
    results = []
    en_idx = lang_map.get('en', -1)

    if en_idx != -1:
        for l_name, l_idx in lang_map.items():
            if l_name == 'en': continue
            if l_idx >= len(mean_gamma): continue

            for p_idx, p_name in enumerate(prompts):
                if p_idx >= len(mean_beta): break

                base_diff = mean_beta[p_idx]
                trans_cost = mean_tau[p_idx, l_idx]
                lang_diff = base_diff + mean_gamma[l_idx] + trans_cost
                is_anchor = (tau_mask[p_idx, l_idx].item() == 0.0)

                results.append({
                    'prompt': p_name,
                    'language': l_name,
                    'Base_Difficulty': base_diff,
                    'Lang_Difficulty': lang_diff,
                    'Safety_Tax': trans_cost,
                    'Is_Anchor': is_anchor
                })

    res_df = pd.DataFrame(results)
    res_df.to_csv(SAVE_RESULTS_FILE, index=False)
    print(f"   Saved results to '{SAVE_RESULTS_FILE}' ({len(res_df)} rows)")

# ==============================================================================
# 3. VISUALIZATION LOGIC
# ==============================================================================
def plot_results():
    print(f"\n🎨 Generating Visualization '{SAVE_PLOT_FILE}'...")

    if not os.path.exists(SAVE_RESULTS_FILE):
        print("❌ Error: Results file not found.")
        return

    res_df = pd.read_csv(SAVE_RESULTS_FILE)
    target_langs = res_df["language"].unique()
    n_langs = len(target_langs)

    fig, axes = plt.subplots(1, n_langs, figsize=(6 * n_langs, 6), sharex=True, sharey=True)
    if n_langs == 1: axes = [axes]

    min_val = min(res_df["Base_Difficulty"].min(), res_df["Lang_Difficulty"].min())
    max_val = max(res_df["Base_Difficulty"].max(), res_df["Lang_Difficulty"].max())
    palette = sns.color_palette("tab10")

    for i, lang in enumerate(target_langs):
        ax = axes[i]
        lang_data = res_df[res_df["language"] == lang]
        anchors = lang_data[lang_data["Is_Anchor"]]
        non_anchors = lang_data[~lang_data["Is_Anchor"]]

        sns.scatterplot(data=non_anchors, x="Base_Difficulty", y="Lang_Difficulty",
                        ax=ax, alpha=0.5, color=palette[i % 10], label="Normal")

        if not anchors.empty:
            sns.scatterplot(data=anchors, x="Base_Difficulty", y="Lang_Difficulty",
                            ax=ax, color="black", marker="*", s=100, label="Anchor")

        ax.plot([min_val, max_val], [min_val, max_val], "r--", label="Equal Difficulty")

        taxed_rate = (non_anchors["Lang_Difficulty"] > non_anchors["Base_Difficulty"]).mean()
        ax.set_title(f"{lang.upper()} (Taxed: {taxed_rate:.1%})", fontsize=14, fontweight="bold")
        ax.set_xlabel(r"English Difficulty ($\beta_i$)")
        if i == 0: ax.set_ylabel("Target Difficulty")
        ax.grid(True, alpha=0.3)
        ax.legend()

    plt.suptitle("Bayesian Safety Cost (Binary Model)", fontsize=16)
    plt.tight_layout()
    plt.savefig(SAVE_PLOT_FILE, dpi=300)
    print(f"✅ Saved plot to '{SAVE_PLOT_FILE}'")

# ==============================================================================
# MAIN EXECUTION
# ==============================================================================
if __name__ == "__main__":
    try:
        import pyro
    except ImportError:
        print("Installing pyro-ppl...")
        os.system("pip install pyro-ppl")
        import pyro

    train_and_extract()
    plot_results()